version: '2'
services:
  backend:
    build: ./backend
    volumes:
      - "./backend:/backend"
    ports:
      - "3000:3000"
    links:
      - "db"
  db:
    image: mysql
    volumes:
     - ./mysql:/var/lib/mysql
    environment:
     - MYSQL_USER=dev
     - MYSQL_PASSWORD=dev
     - MYSQL_DATABASE=pro_habits
     - MYSQL_USER=developer
     - MYSQL_PASSWORD=developer
     - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
  myadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db:db
    ports:
      - "4022:80"
    environment:
      - PMA_HOST=db
